### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by juliusroeder** [psalvaggio/cppregpattern#1]
Hi Philip, 
Would you mind putting a license on this? :)
Then the code can be reused in other projects.Otherwise the default copyright applies which means [no one may reproduce, distribute, or create derivatives.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).
Thank you. 
Julius

**Comment by psalvaggio** [comment]
Done. Pushed a new 1.0.1 release with the license.
